on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: gstracquadanio
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/stracquadaniolab/latex:latest, ghcr.io/stracquadaniolab/latex:v0.1.0
      - name: Push to registry
        if: startsWith(github.event.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/stracquadaniolab/latex:latest, ghcr.io/stracquadaniolab/latex:v0.1.0